name: Build APK

on:
  push:
    paths-ignore:
      - "**/*.md"
      - "kitx_mobile/.*/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".*/**"
      - "**/*.md"
      - "kitx_mobile/.*/**"

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Build
        working-directory: kitx_mobile
        run: |
          python build.py

          echo "DATA=$(cat data.json)" >> $GITHUB_ENV

      - name: Add Artifacts SHA1
        working-directory: kitx_mobile
        run: |-
          echo "## Artifact SHA1 List" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "```" >> $GITHUB_STEP_SUMMARY
          echo "${{ join(fromJSON(env.DATA).sha1, '" >> $GITHUB_STEP_SUMMARY
          echo "') }}" >> $GITHUB_STEP_SUMMARY
          echo "```" >> $GITHUB_STEP_SUMMARY
          

      - name: Upload Artifacts
        uses: nanoufo/action-upload-artifacts-and-release-assets@main
        with:
          path: |-
            ${{ join(fromJSON(env.DATA).publish_list, '
            ') }}

      # - uses: actions/upload-artifact@v3
      #   with:
      #     path: kitx_mobile/.ci_cd/*.apk

      # - uses: actions/upload-artifact@v3
      #   with:
      #     path: kitx_mobile/.ci_cd/*.sha1

      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: kitx-mobile-arm64-v8a-release.apk
      #     path: kitx_mobile/.ci_cd/kitx-mobile-arm64-v8a-release.apk

      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: kitx-mobile-armeabi-v7a-release.apk
      #     path: kitx_mobile/.ci_cd/kitx-mobile-armeabi-v7a-release.apk

      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: kitx-mobile-x86_64-release.apk
      #     path: kitx_mobile/.ci_cd/kitx-mobile-x86_64-release.apk

      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: kitx-mobile-release.apk
      #     path: kitx_mobile/.ci_cd/kitx-mobile-release.apk

      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: apk signatures
      #     path: kitx_mobile/.ci_cd/*.sha1
